# Generated by Django 4.2.18 on 2025-01-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField(max_length=4)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('counter', models.IntegerField()),
                ('collected', models.BooleanField(default=False)),
            ],
        ),
    ]
