# Generated by Django 4.2.18 on 2025-01-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbercollection',
            name='bill_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='numbercollection',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
