# Generated by Django 4.2.18 on 2025-01-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_numbercollection_bill_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbercollection',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
