# Generated by Django 4.2.18 on 2025-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_numbercollection_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbercollection',
            name='counter',
            field=models.IntegerField(default=2),
        ),
    ]
