# Generated by Django 4.2.18 on 2025-02-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_numbercollection_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbercollection',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
    ]
